// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjxo8xDmCjJAW_QxICPr2R65ZbTX_S9mQ',
    appId: '1:88186335632:web:3f8c9f2916b18761bb0315',
    messagingSenderId: '88186335632',
    projectId: 'project-arm-app',
    authDomain: 'project-arm-app.firebaseapp.com',
    storageBucket: 'project-arm-app.firebasestorage.app',
    measurementId: 'G-4Z90LR8Z93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5EXH2512zpXXwG2zyMyb8VGSZB1Xhpck',
    appId: '1:88186335632:android:068ae4931868c78fbb0315',
    messagingSenderId: '88186335632',
    projectId: 'project-arm-app',
    storageBucket: 'project-arm-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7UAj0x9EdLZDF5GYmSoPB4mU7Zn1KdhU',
    appId: '1:88186335632:ios:893c78345cc96581bb0315',
    messagingSenderId: '88186335632',
    projectId: 'project-arm-app',
    storageBucket: 'project-arm-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7UAj0x9EdLZDF5GYmSoPB4mU7Zn1KdhU',
    appId: '1:88186335632:ios:893c78345cc96581bb0315',
    messagingSenderId: '88186335632',
    projectId: 'project-arm-app',
    storageBucket: 'project-arm-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjxo8xDmCjJAW_QxICPr2R65ZbTX_S9mQ',
    appId: '1:88186335632:web:a5621b136b78fe83bb0315',
    messagingSenderId: '88186335632',
    projectId: 'project-arm-app',
    authDomain: 'project-arm-app.firebaseapp.com',
    storageBucket: 'project-arm-app.firebasestorage.app',
    measurementId: 'G-1CMMMN1S5G',
  );
}
